Update Request Matching.md
wiremock/wiremock.org pull request #223
Opened 2023-10-29 05:29 UTC by Smartmind12

Adding codetabs as part of issue 183.

## References

- Part of #183 

## Submitter checklist

- [X] The PR request is well described and justified, including the body and the references
- [ ] The PR title represents the desired changelog entry
- [ ] If the change against WireMock 2 functionality (incompatible with WireMock 3),
      it is submitted against the [2.x](https://github.com/wiremock/wiremock.org/tree/2.x) branch
- [ ] The repository's code style is followed (see the contributing guide)

_Details: [Contributor Guide](https://github.com/wiremock/wiremock.org/blob/main/CONTRIBUTING.md)_

2023-10-29 16:20 UTC, oleg-nenashev reviewed
```
  Liquid Exception: Liquid syntax error (line 645): Unknown tag 'endcodetab' in /home/runner/work/wiremock.org/wiremock.org/_docs/request-matching.md
                    ------------------------------------------------
      Jekyll 4.3.2   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
```

2023-10-29 16:21 UTC, oleg-nenashev commented on _docs/request-matching.md
> +{% endcodetabs %}
Mistake here

2023-10-30 09:58 UTC, oleg-nenashev requested changes
Requesting changes based on the comment above

2023-10-30 13:55 UTC, Smartmind12 commented on _docs/request-matching.md
> +{% endcodetabs %}
Yes I have editted it!

2024-02-02 16:49 UTC, tomakehurst commented
Closing this as we're migrating the docs to mkdocs with a new tabbed code feature.

2024-02-02 16:49 UTC, closed without merging