Add custom content patterns.
wiremock/wiremock.org pull request #285
Opened 2024-06-04 16:41 UTC by kyle-winkelman

Demonstrate how users can create `ContentPatternExtension`s for extending WireMock's matching abilities.

## References

- https://github.com/wiremock/wiremock/pull/2592

## Submitter checklist

- [x] The PR request is well described and justified, including the body and the references
- [ ] The PR title represents the desired changelog entry
- [ ] If the change against WireMock 2 functionality (incompatible with WireMock 3),
      it is submitted against the [2.x](https://github.com/wiremock/wiremock.org/tree/2.x) branch
- [x] The repository's code style is followed (see the contributing guide)

_Details: [Contributor Guide](https://github.com/wiremock/wiremock.org/blob/main/CONTRIBUTING.md)_

2024-11-04 18:51 UTC, oleg-nenashev requested changes
The content itself looks good to me, but a redirect is needed.
P.S: I am no longer a maintainer of this repo, just passing by

2024-11-04 18:51 UTC, oleg-nenashev commented on _data/doc-categories.yml
> +    - extensibility/custom-content-matching
If implemented as is, it breaks the original page access. At least a redirect is needed in the markdown file

2024-11-10 16:05 UTC, leeturner commented on _docs/extensibility/custom-request-matching.md
> +title: Custom Request Matching
This all looks fine.  @oleg-nenashev is correct about the redirect though.  Changing the name of the file will change the url structure so all the indexed pages in the search engines will return a 404.  If you take a look at the other pages on the site, some of them have a `redirect_from` element in the front matter.  This is what we need here

2025-01-16 10:44 UTC, merged

2025-01-16 10:45 UTC, leeturner commented
Thank you for the contribution.  I will add the redirect as a separate update before publishing the site

2025-01-16 13:07 UTC, kyle-winkelman commented
This PR should not have been merged. The original PR, wiremock/wiremock#2592 (as noted in the references), was never merged and so this content should not be published.

2025-01-16 13:28 UTC, leeturner commented
Ah, sorry.  My bad

2025-01-16 13:30 UTC, leeturner commented
Will see if I can revert it

2025-01-16 13:49 UTC, leeturner commented
Couldn't automatically revert the PR due to the redirect I added so I have backed out the changes in a separate PR - https://github.com/wiremock/wiremock.org/pull/333 

Sorry for the hassle.  Would you be able to raise the PR again ?